---
extends:
  - airbnb

# Suppress lots of rules, treat as warnings. Revisit them later.
rules:
  prefer-rest-params: [1]
  import/no-unresolved: [1]
  react/sort-comp: [1]
  react/prefer-es6-class: [1]
  react/prefer-stateless-function: [1]
