version: 0.0.0.{build}

shallow_clone: true

init:
  - ps: if ($env:APPVEYOR_REPO_TAG_NAME) { Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME.Substring(1) }

platform:
  - Any CPU

configuration:
  - Release

matrix:
  fast_finish: true

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - packages -> **\packages.config
  - node_modules -> package.json
  - Nancy.ViewEngines.React\node_modules -> Nancy.ViewEngines.React\package.json
  - Nancy.ViewEngines.React.Example\node_modules -> Nancy.ViewEngines.React.Example\package.json
  - Nancy.ViewEngines.React.UnitTests\node_modules -> Nancy.ViewEngines.React.UnitTests\package.json

before_build:
  - ps: nuget restore Nancy.ViewEngines.React.sln

before_test:
  - ps: Nancy.ViewEngines.React.UnitTests\Test-JavaScript.ps1
  - cinst googlechrome

artifacts:
  - path: 'Nancy.ViewEngines.React\**\*.nupkg'

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

deploy:
  - release: v$(APPVEYOR_BUILD_VERSION)
    provider: GitHub
    draft: false
    prerelease: false
    auth_token:
      secure: cApkFZuYfz7loLotMfbhb53ZIfjjfbY7dr46eu6Q9+yAV+KuSGYGcVTG8Bgx8wka
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: iBKdOaX4b1BDwWzGKoqbHoJHyOAxL6EHCRIretKb16QRLm5l1nkaF+W0SGfuEfMY
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    server: https://www.myget.org/F/lijunle/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/lijunle
    api_key:
      secure: 8wzaNPk1mfp5TWFmpGIAs7XRcB9LF9NJKMkdm0oUN1q6SwQ/VVd6r9WPcDm0IXlu
    on:
      branch: master
