---
extends:
  - airbnb

parser: espree

parserOptions:
  ecmaVersion: 5
  sourceType: script
  ecmaFeatures:
    globalReturn: false
    generators: false
    jsx: false

rules:
  no-var: 0
  vars-on-top: 0
  object-shorthand: 0
  prefer-template: 0
  prefer-rest-params: 0
  prefer-arrow-callback: 0
